version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:16
    user: root
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    env_file:
      - .env.development
    volumes:
      - postgres_turbo_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - turbo-network

  turbo:
    container_name: turbo-nextjs-strapi
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "1337:1337"
    env_file:
      - .env.development
    environment:
      - STRAPI_VERSION=4.17.1
    volumes:
      - ./:/app/
      - /app/node_modules/
    restart: on-failure
    networks:
      - turbo-network

networks:
  turbo-network:
    driver: bridge
volumes:
  postgres_turbo_data:
